### ISSUE TITLE
Jekyll error with local build

### ISSUE THREAD

**Issue by lachlandeer** [carpentries/maintainer-onboarding#24] opened 2018-03-22 14:02 UTC
Hi

Getting an error when trying to serve this material locally. Upon running `make serve` from the command line, I get the following output:

```{bash}
jekyll serve
Configuration file: /home/lachlan/teaching/swc/maintainer-onboarding/material/maintainer-onboarding/_config.yml
            Source: /home/lachlan/teaching/swc/maintainer-onboarding/material/maintainer-onboarding
       Destination: /home/lachlan/teaching/swc/maintainer-onboarding/material/maintainer-onboarding/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error: Unknown tag 'link' in _includes/navbar.html, included in _layouts/base.html
jekyll 3.0.1 | Error:  Liquid syntax error: Unknown tag 'link'
Makefile:21: recipe for target 'serve' failed
make: *** [serve] Error 1
```

I am running this on Ubuntu 16.04 with the following versions of software:

* ruby version 2.3.1
* gem version 2.5.2.1
* jekyll version 3.0.1

I have tried to build a different repository (`git-novice`) and it ran through.

Best

Lachlan

**Comment by katrinleinweber** [comment] 2018-03-22 14:24
Hi! What happens if you replace all occurances of `{% link ... %}` with `/...` with ... bein the filenames. Haven't tested this; Just a hunch, because I'm working with another templates right now and also has some issues with those `{` placeholders `}`.

**Comment by rgaiacs** [comment] 2018-03-22 16:01
Please update your Jekyll installation to 3.2 or higher. `link` was introduced in 3.2.0, see [the release note](https://jekyllrb.com/news/2016/07/26/jekyll-3-2-0-released/). From August 23, 2016 GitHub Pages uses Jekyll 3.2, see [this blog post](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2), so `link` is available to use in our current workflow.

@ErinBecker You can close this issue as not a bug.

**Comment by lachlandeer** [comment] 2018-03-22 16:19
Thanks - updating jekyll worked.

As a hint for future maintainer onboarding for those using Ubuntu 16.04:

- `sudo apt-get install jekyll` installs version 3.0.1 which won't build all SWC/DC lessons
- instead encourage the following:
    * install ruby-dev: `sudo apt-get install ruby-dev`
    * install jekyll via gem `sudo gem install jekyll bundler`

Then we get a recent version of jekyll. At first I didn't install `ruby-dev` and it threw an error.

**Comment by ErinBecker** [comment] 2023-04-17 21:49
I've been very remiss in keeping the issues updated in this repository. My apologies. With the recent transfer of this repo to The Carpentries Workbench, jekyll is no longer a requirement for building locally. Closing.

**Closed by ErinBecker** 2023-04-17 21:49 UTC
